spring.application.name=MediConnect_Project

# ==========================================
# CONEXION A POSTGRESQL (Session pooler, IPv4 compatible con Render)
# ==========================================

spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.phmmyntqgxwqefrrckqt
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=mediconnect

# Dialecto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# LOGS
# ==========================================

logging.level.root=INFO

# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}

# ==========================================
# THYMELEAF
# ==========================================

spring.thymeleaf.cache=false

# ==========================================
# SERVIDOR
# ==========================================

server.port=${PORT:8080}
