spring.application.name=MediConnect_Project


# ==========================================
# CONEXION A POSTGRESQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/HealthLink
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# LOGS
# ==========================================

logging.level.root=INFO
logging.file.name=logs/api.log

# ==========================================
# JWT
# ==========================================

jwt.secret=mediconnect-clave-secreta-para-jwt-de-prueba-2026-grupo3

# ==========================================
# THYMELEAF
# ==========================================

spring.thymeleaf.cache=false

# ==========================================
# SERVIDOR
# ==========================================

server.port=8080